spring:
  application:
    name: GodsChoice

  profiles:
    active: dev

game:
  rule:
    # 시간 (초)
    start-delay: 3 #GAME_START_DELAY_SECONDS = 3;
    loading-timeout: 5 #LOADING_TIMEOUT_SECONDS
    oracle-phase: 8 #ORACLE_PHASE_SECONDS
    card-send-delay: 3 #CARD_SEND_DELAY_SECONDS
    card-select-time: 120 #CARD_SELECT_DURATION_SECONDS
    vote-proposal-time: 15 #VOTE_PROPOSAL_SECONDS
    trial-time: 60 #TRIAL_DURATION_SECONDS
    round-result-duration: 35 #ROUND_RESULT_DURATION_SECONDS
    next-round-delay: 5
    vote-fail-delay: 3
    game-over-cleanup-time: 60

    # 룰
    card-count : 4 #CARD_COUNT
    max-rounds: 4
    initial-hp: 500
    max-player-count: 4

    # 닉네임
    nickname-min-length: 2
    nickname-max-length: 6

    # 점수
    trial-start-penalty: 50 #TRIAL_START_PENALTY
    traitor-catch-reward: 100
    citizen-fail-penalty: 100